---

dist: trusty
sudo: false
language: generic
services:
  - docker

git:
  depth: 1
  submodules: false

stages:
  - test
  - publish

script:
  - sudo apt update || true # allow partial updates as well
  - sudo apt install -y realpath gettext
  - ./bin/ci.sh run


