--- 
version: '3'

services: 
  nginx: 
    image: ${IMAGE}
    restart: always
    command:
      - start
      - nginx
    ports:
      - "8480:80"
    environment:
      PHPFPM_HOST: "phpfpm"

  phpfpm: 
    image: ${IMAGE}
    restart: always
    command:
      - start
      - phpfpm
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "matomouser"
      MYSQL_PASSWORD: "test123"

  mysql:
    image: "mariadb:10.2.14"
    restart: always
    environment:
      MYSQL_USER: "matomouser"
      MYSQL_PASSWORD: "test123"
      MYSQL_ROOT_PASSWORD: "test1234"
      MYSQL_DATABASE: "matomo"
