--- 
version: '3'

services: 
  nginx: 
    image: ${IMAGE}
    command:
      - start
      - nginx
    ports:
      - "8480:80"
    environment:
      PHPFPM_HOST: "phpfpm"

  phpfpm: 
    image: ${IMAGE}
    command:
      - start
      - phpfpm

  # mysql:
  #   image: "mysql:5.6"
  #   restart: always
  #   #deactivate sql mode 'only_full_group_by', otherwise inhouseportal won't work correctly
  #   command:
  #     - mysqld
  #     - "--sql_mode=\"\""
  #   environment:
  #     - MYSQL_USER
  #     - MYSQL_PASSWORD
  #     - MYSQL_ROOT_PASSWORD
  #   volumes:
  #     - ./dump:/docker-entrypoint-initdb.d
